"""empty message

Revision ID: 02e07e388520
Revises: eb2cffb2a32d
Create Date: 2024-07-22 15:26:48.025396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02e07e388520'
down_revision = 'eb2cffb2a32d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('building_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accrued_metal', sa.Integer(), nullable=True))
        batch_op.drop_column('accrued_metai')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('building_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accrued_metai', sa.INTEGER(), nullable=True))
        batch_op.drop_column('accrued_metal')

    # ### end Alembic commands ###
