"""empty message

Revision ID: 12033597bfc5
Revises: 68133976ccf9
Create Date: 2024-07-05 13:23:29.263336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12033597bfc5'
down_revision = '68133976ccf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_game_rewards_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reward_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['test_game_items.id'], ),
    sa.ForeignKeyConstraint(['reward_id'], ['test_game_rewards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_game_rewards_items')
    # ### end Alembic commands ###
