"""empty message

Revision ID: 1dc48eb0e28d
Revises: f51672a62840
Create Date: 2024-07-09 23:29:37.876166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dc48eb0e28d'
down_revision = 'f51672a62840'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_level_xp_required', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_game', schema=None) as batch_op:
        batch_op.drop_column('next_level_xp_required')

    # ### end Alembic commands ###
