"""empty message

Revision ID: 1e099ba0143f
Revises: c7b9399e3d00
Create Date: 2024-07-11 11:57:37.469747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e099ba0143f'
down_revision = 'c7b9399e3d00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_game_building_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xp_per_hour', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wood_per_hour', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stone_per_hour', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('metal_per_hour', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('accrual_start_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('max_accrual_duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('accrued_xp', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('accrued_cash', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('accrued_wood', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('accrued_stone', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('accrued_metai', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_game_building_progress', schema=None) as batch_op:
        batch_op.drop_column('accrued_metai')
        batch_op.drop_column('accrued_stone')
        batch_op.drop_column('accrued_wood')
        batch_op.drop_column('accrued_cash')
        batch_op.drop_column('accrued_xp')
        batch_op.drop_column('max_accrual_duration')
        batch_op.drop_column('accrual_start_time')
        batch_op.drop_column('metal_per_hour')
        batch_op.drop_column('stone_per_hour')
        batch_op.drop_column('wood_per_hour')
        batch_op.drop_column('xp_per_hour')

    # ### end Alembic commands ###
