"""empty message

Revision ID: 21f5ad6ceee9
Revises: 0fea3c158dd5
Create Date: 2024-06-27 22:39:29.706538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21f5ad6ceee9'
down_revision = '0fea3c158dd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gtn_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gtn_history', schema=None) as batch_op:
        batch_op.drop_column('number')

    # ### end Alembic commands ###
