"""empty message

Revision ID: 31602f92f07e
Revises: a249b09e0ffe
Create Date: 2024-07-17 19:46:51.117535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31602f92f07e'
down_revision = 'a249b09e0ffe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gtn_settings')
    op.drop_table('gtn_history')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gtn_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('entry_date', sa.DATETIME(), nullable=True),
    sa.Column('startrange', sa.INTEGER(), nullable=True),
    sa.Column('endrange', sa.INTEGER(), nullable=True),
    sa.Column('number', sa.INTEGER(), nullable=True),
    sa.Column('guesses', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gtn_settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('startrange', sa.INTEGER(), nullable=True),
    sa.Column('endrange', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
