"""empty message

Revision ID: 3fc6cd0d160b
Revises: 5071fcd7a9a5
Create Date: 2024-07-15 19:38:00.838870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fc6cd0d160b'
down_revision = '5071fcd7a9a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_game_buildings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_xp_per_minute', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('base_cash_per_minute', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('base_wood_per_minute', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('base_stone_per_minute', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('base_metal_per_minute', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_game_buildings', schema=None) as batch_op:
        batch_op.drop_column('base_metal_per_minute')
        batch_op.drop_column('base_stone_per_minute')
        batch_op.drop_column('base_wood_per_minute')
        batch_op.drop_column('base_cash_per_minute')
        batch_op.drop_column('base_xp_per_minute')

    # ### end Alembic commands ###
