"""empty message

Revision ID: 45b14be46578
Revises: 8cfdc5fd66e0
Create Date: 2024-07-15 10:42:32.515922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45b14be46578'
down_revision = '8cfdc5fd66e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_game_building_progress', schema=None) as batch_op:
        batch_op.drop_column('base_building_stone_required')
        batch_op.drop_column('base_building_xp_required')
        batch_op.drop_column('base_building_metal_required')
        batch_op.drop_column('base_building_wood_required')
        batch_op.drop_column('base_building_cash_required')
        batch_op.drop_column('base_building_level_required')

    with op.batch_alter_table('test_game_buildings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_building_cash_required', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('base_building_level_required', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('base_building_xp_required', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('base_building_wood_required', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('base_building_stone_required', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('base_building_metal_required', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_game_buildings', schema=None) as batch_op:
        batch_op.drop_column('base_building_metal_required')
        batch_op.drop_column('base_building_stone_required')
        batch_op.drop_column('base_building_wood_required')
        batch_op.drop_column('base_building_xp_required')
        batch_op.drop_column('base_building_level_required')
        batch_op.drop_column('base_building_cash_required')

    with op.batch_alter_table('test_game_building_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_building_level_required', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('base_building_cash_required', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('base_building_wood_required', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('base_building_metal_required', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('base_building_xp_required', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('base_building_stone_required', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
