"""empty message

Revision ID: 49a964610261
Revises: 640de824f736
Create Date: 2024-07-02 18:45:23.224769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49a964610261'
down_revision = '640de824f736'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('game_name', sa.String(length=64), nullable=True),
    sa.Column('game_exists', sa.Boolean(), nullable=True),
    sa.Column('entry_date', sa.DateTime(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('cash', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_game_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=64), nullable=True),
    sa.Column('item_cost', sa.Float(), nullable=True),
    sa.Column('item_xp', sa.Integer(), nullable=True),
    sa.Column('item_level', sa.Integer(), nullable=True),
    sa.Column('item_type', sa.String(length=64), nullable=True),
    sa.Column('item_description', sa.String(length=256), nullable=True),
    sa.Column('testgame_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['testgame_id'], ['test_game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_game_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('test_game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['test_game_items.id'], ),
    sa.ForeignKeyConstraint(['test_game_id'], ['test_game.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_game_inventory')
    op.drop_table('test_game_items')
    op.drop_table('test_game')
    # ### end Alembic commands ###
