"""empty message

Revision ID: 5071fcd7a9a5
Revises: 45b14be46578
Create Date: 2024-07-15 10:55:24.796277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5071fcd7a9a5'
down_revision = '45b14be46578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_game_building_progress', schema=None) as batch_op:
        batch_op.drop_column('max_building_level')

    with op.batch_alter_table('test_game_buildings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_building_level', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_game_buildings', schema=None) as batch_op:
        batch_op.drop_column('max_building_level')

    with op.batch_alter_table('test_game_building_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_building_level', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
