"""empty message

Revision ID: 50b8b8fce3ff
Revises: bdfe497713b0
Create Date: 2024-07-07 20:33:03.173252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50b8b8fce3ff'
down_revision = 'bdfe497713b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_game_buildings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('building_link', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_game_buildings', schema=None) as batch_op:
        batch_op.drop_column('building_link')

    # ### end Alembic commands ###
