"""empty message

Revision ID: 512e1a43a6e8
Revises: 1e099ba0143f
Create Date: 2024-07-11 12:07:52.440110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '512e1a43a6e8'
down_revision = '1e099ba0143f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_game_resource_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_game_id', sa.Integer(), nullable=True),
    sa.Column('cash', sa.Float(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('wood', sa.Integer(), nullable=True),
    sa.Column('stone', sa.Integer(), nullable=True),
    sa.Column('metal', sa.Integer(), nullable=True),
    sa.Column('entry_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['test_game_id'], ['test_game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wood', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stone', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('metal', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_game', schema=None) as batch_op:
        batch_op.drop_column('metal')
        batch_op.drop_column('stone')
        batch_op.drop_column('wood')

    op.drop_table('test_game_resource_log')
    # ### end Alembic commands ###
