"""empty message

Revision ID: 53699ee9f2d0
Revises: b21a51e3acb6
Create Date: 2024-08-05 10:07:22.713863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53699ee9f2d0'
down_revision = 'b21a51e3acb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quest_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=True),
    sa.Column('game_level', sa.Integer(), nullable=True),
    sa.Column('cash', sa.Integer(), nullable=True),
    sa.Column('wood', sa.Integer(), nullable=True),
    sa.Column('stone', sa.Integer(), nullable=True),
    sa.Column('metal', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quest_prerequisites_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quest_progress_id', sa.Integer(), nullable=True),
    sa.Column('quest_prerequisite_id', sa.Integer(), nullable=True),
    sa.Column('prerequisite_completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['quest_prerequisite_id'], ['quest_prerequisites.id'], ),
    sa.ForeignKeyConstraint(['quest_progress_id'], ['quest_progress.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quest_requirements_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quest_progress_id', sa.Integer(), nullable=True),
    sa.Column('quest_requirement_id', sa.Integer(), nullable=True),
    sa.Column('requirement_completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['quest_progress_id'], ['quest_progress.id'], ),
    sa.ForeignKeyConstraint(['quest_requirement_id'], ['quest_requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quest_prerequisites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_level', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quest_prerequisites', schema=None) as batch_op:
        batch_op.drop_column('game_level')

    op.drop_table('quest_requirements_progress')
    op.drop_table('quest_prerequisites_progress')
    op.drop_table('quest_requirements')
    # ### end Alembic commands ###
