"""empty message

Revision ID: 640de824f736
Revises: eebccca79007
Create Date: 2024-07-02 18:43:27.200727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '640de824f736'
down_revision = 'eebccca79007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_game')
    op.drop_table('test_game_inventory_1')
    op.drop_table('test_game_items')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_game_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('item_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('item_cost', sa.FLOAT(), nullable=True),
    sa.Column('item_xp', sa.INTEGER(), nullable=True),
    sa.Column('item_level', sa.INTEGER(), nullable=True),
    sa.Column('item_type', sa.VARCHAR(length=64), nullable=True),
    sa.Column('item_description', sa.VARCHAR(length=256), nullable=True),
    sa.Column('testgame_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['testgame_id'], ['test_game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_game_inventory_1',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('item_id', sa.INTEGER(), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('test_game_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['test_game_items.id'], ),
    sa.ForeignKeyConstraint(['test_game_id'], ['test_game.id'], name='fk_test_game_inventory_test_game'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_game',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('game_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('game_exists', sa.BOOLEAN(), nullable=True),
    sa.Column('entry_date', sa.DATETIME(), nullable=True),
    sa.Column('xp', sa.INTEGER(), nullable=True),
    sa.Column('level', sa.INTEGER(), nullable=True),
    sa.Column('cash', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
