"""empty message

Revision ID: 64a482e9451c
Revises: 9960d60b3be1
Create Date: 2024-08-09 10:20:00.763399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64a482e9451c'
down_revision = '9960d60b3be1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hero_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_type_name', sa.String(length=64), nullable=True),
    sa.Column('hero_type_description', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rarity_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rarity_type_name', sa.String(length=64), nullable=True),
    sa.Column('rarity_type_description', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('heroes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_type_id', sa.Integer(), nullable=True),
    sa.Column('hero_name', sa.String(length=64), nullable=True),
    sa.Column('hero_description', sa.String(length=256), nullable=True),
    sa.Column('hero_link', sa.String(length=256), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('rarity_id', sa.Integer(), nullable=True),
    sa.Column('health', sa.Integer(), nullable=True),
    sa.Column('attack', sa.Integer(), nullable=True),
    sa.Column('defense', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hero_type_id'], ['hero_types.id'], ),
    sa.ForeignKeyConstraint(['rarity_id'], ['rarity_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hero_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('hero_id', sa.Integer(), nullable=True),
    sa.Column('hero_level', sa.Integer(), nullable=True),
    sa.Column('hero_active', sa.Boolean(), nullable=True),
    sa.Column('hero_xp', sa.Integer(), nullable=True),
    sa.Column('hero_health', sa.Integer(), nullable=True),
    sa.Column('hero_attack', sa.Integer(), nullable=True),
    sa.Column('hero_defense', sa.Integer(), nullable=True),
    sa.Column('hero_speed', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['hero_id'], ['heroes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hero_progress')
    op.drop_table('heroes')
    op.drop_table('rarity_types')
    op.drop_table('hero_types')
    # ### end Alembic commands ###
