"""empty message

Revision ID: 69362b36ba44
Revises: 4e61c10ea67e
Create Date: 2024-06-18 08:16:10.955162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69362b36ba44'
down_revision = '4e61c10ea67e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('fk_firstname',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('fk_surname',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('fk_dob',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('fk_firstlineaddress',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('fk_city',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('fk_postcode',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('fk_postcode',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('fk_city',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('fk_firstlineaddress',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('fk_dob',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('fk_surname',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('fk_firstname',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    # ### end Alembic commands ###
