"""empty message

Revision ID: 6a5a128e4a04
Revises: 34cbe8ee8512
Create Date: 2024-07-08 14:37:17.114736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a5a128e4a04'
down_revision = '34cbe8ee8512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_game_buildings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('building_description', sa.String(length=256), nullable=True))
        batch_op.drop_column('building_descriptions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_game_buildings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('building_descriptions', sa.VARCHAR(length=256), nullable=True))
        batch_op.drop_column('building_description')

    # ### end Alembic commands ###
