"""empty message

Revision ID: 79827f5f13a5
Revises: 50b8b8fce3ff
Create Date: 2024-07-07 22:14:39.903962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79827f5f13a5'
down_revision = '50b8b8fce3ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_game_building_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('building_level', sa.Integer(), nullable=True),
    sa.Column('level_required', sa.Integer(), nullable=True),
    sa.Column('cash_required', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['test_game_buildings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_game_building_requirements')
    # ### end Alembic commands ###
