"""empty message

Revision ID: 7d42b39eb421
Revises: bb81f02dc5b8
Create Date: 2024-07-08 20:51:57.794296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d42b39eb421'
down_revision = 'bb81f02dc5b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_game_building_requirements')
    with op.batch_alter_table('test_game_building_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_building_cash_required', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('base_building_level_required', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_game_building_progress', schema=None) as batch_op:
        batch_op.drop_column('base_building_level_required')
        batch_op.drop_column('base_building_cash_required')

    op.create_table('test_game_building_requirements',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('building_id', sa.INTEGER(), nullable=True),
    sa.Column('building_level', sa.INTEGER(), nullable=True),
    sa.Column('user_level_required', sa.INTEGER(), nullable=True),
    sa.Column('user_cash_required', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['test_game_buildings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
