"""empty message

Revision ID: 7dce0ebefee1
Revises: e0386229ccea
Create Date: 2024-07-22 21:32:49.863846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dce0ebefee1'
down_revision = 'e0386229ccea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quest_rewards', schema=None) as batch_op:
        batch_op.drop_column('quest_reward_name')
        batch_op.drop_column('quest_reward_description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quest_rewards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quest_reward_description', sa.VARCHAR(length=256), nullable=True))
        batch_op.add_column(sa.Column('quest_reward_name', sa.VARCHAR(length=64), nullable=True))

    # ### end Alembic commands ###
