"""empty message

Revision ID: 8cfdc5fd66e0
Revises: 67eb132d7754
Create Date: 2024-07-15 08:48:48.365205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cfdc5fd66e0'
down_revision = '67eb132d7754'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_game_building_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_building_level', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_game_building_progress', schema=None) as batch_op:
        batch_op.drop_column('max_building_level')

    # ### end Alembic commands ###
