"""empty message

Revision ID: 910d8bcc3be6
Revises: b1e7b04862dc
Create Date: 2024-07-03 12:06:44.603979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '910d8bcc3be6'
down_revision = 'b1e7b04862dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_game_level_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('xp_required', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_game_level_requirements')
    # ### end Alembic commands ###
