"""empty message

Revision ID: 98ec5d5e1c30
Revises: a83e307f7113
Create Date: 2024-06-19 11:49:09.934984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98ec5d5e1c30'
down_revision = 'a83e307f7113'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.alter_column('account_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('transaction_date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstname', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('surname', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('dob', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('firstlineaddress', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('postcode', sa.String(length=64), nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_column('fk_firstlineaddress')
        batch_op.drop_column('fk_city')
        batch_op.drop_column('fk_surname')
        batch_op.drop_column('fk_postcode')
        batch_op.drop_column('fk_firstname')
        batch_op.drop_column('fk_dob')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_dob', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('fk_firstname', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('fk_postcode', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('fk_surname', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('fk_city', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('fk_firstlineaddress', sa.VARCHAR(length=64), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.drop_column('postcode')
        batch_op.drop_column('city')
        batch_op.drop_column('firstlineaddress')
        batch_op.drop_column('dob')
        batch_op.drop_column('surname')
        batch_op.drop_column('firstname')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('transaction_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('account_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    # ### end Alembic commands ###
