"""empty message

Revision ID: 9960d60b3be1
Revises: d236ce32f83c
Create Date: 2024-08-05 12:31:33.707525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9960d60b3be1'
down_revision = 'd236ce32f83c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quest_requirements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('building_required', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('building_level_required', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quest_requirements', schema=None) as batch_op:
        batch_op.drop_column('building_level_required')
        batch_op.drop_column('building_required')

    # ### end Alembic commands ###
