"""empty message

Revision ID: b106aea3326c
Revises: d9665ba0efd7
Create Date: 2024-07-03 08:11:12.778582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b106aea3326c'
down_revision = 'd9665ba0efd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_game_xp_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_game_id', sa.Integer(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('entry_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['test_game_id'], ['test_game.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_game_xp_log')
    # ### end Alembic commands ###
