"""empty message

Revision ID: b1a79ee6255e
Revises: 004eee70c78d
Create Date: 2024-07-11 14:05:49.110881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1a79ee6255e'
down_revision = '004eee70c78d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_game_building_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xp_per_minute', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cash_per_minute', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('wood_per_minute', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stone_per_minute', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('metal_per_minute', sa.Integer(), nullable=True))
        batch_op.drop_column('stone_per_hour')
        batch_op.drop_column('wood_per_hour')
        batch_op.drop_column('xp_per_hour')
        batch_op.drop_column('metal_per_hour')
        batch_op.drop_column('cash_per_hour')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_game_building_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cash_per_hour', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('metal_per_hour', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('xp_per_hour', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('wood_per_hour', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('stone_per_hour', sa.INTEGER(), nullable=True))
        batch_op.drop_column('metal_per_minute')
        batch_op.drop_column('stone_per_minute')
        batch_op.drop_column('wood_per_minute')
        batch_op.drop_column('cash_per_minute')
        batch_op.drop_column('xp_per_minute')

    # ### end Alembic commands ###
