"""empty message

Revision ID: b1e7b04862dc
Revises: b106aea3326c
Create Date: 2024-07-03 10:00:49.734183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1e7b04862dc'
down_revision = 'b106aea3326c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_game_cash_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_game_id', sa.Integer(), nullable=True),
    sa.Column('cash', sa.Float(), nullable=True),
    sa.Column('entry_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['test_game_id'], ['test_game.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_game_cash_log')
    # ### end Alembic commands ###
