"""empty message

Revision ID: b21a51e3acb6
Revises: b827da8d2c69
Create Date: 2024-08-04 21:03:04.877574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b21a51e3acb6'
down_revision = 'b827da8d2c69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quest_prerequisites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=True),
    sa.Column('prerequisite_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prerequisite_id'], ['quests.id'], ),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('quest_prequisites')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quest_prequisites',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('quest_id', sa.INTEGER(), nullable=True),
    sa.Column('prequisite_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['prequisite_id'], ['quests.id'], ),
    sa.ForeignKeyConstraint(['quest_id'], ['quests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('quest_prerequisites')
    # ### end Alembic commands ###
