"""empty message

Revision ID: b5e65e5375e1
Revises: 12033597bfc5
Create Date: 2024-07-05 13:27:34.015849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5e65e5375e1'
down_revision = '12033597bfc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reward_item_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reward_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['test_game_items.id'], ),
    sa.ForeignKeyConstraint(['reward_id'], ['test_game_rewards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('test_game_rewards_items')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_game_rewards_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('reward_id', sa.INTEGER(), nullable=True),
    sa.Column('item_id', sa.INTEGER(), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['test_game_items.id'], ),
    sa.ForeignKeyConstraint(['reward_id'], ['test_game_rewards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('reward_item_association')
    # ### end Alembic commands ###
