"""empty message

Revision ID: bdfe497713b0
Revises: 491ad95a487d
Create Date: 2024-07-07 20:30:25.006268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdfe497713b0'
down_revision = '491ad95a487d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_game_buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_name', sa.String(length=64), nullable=True),
    sa.Column('building_description', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_game_building_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('building_progress', sa.Integer(), nullable=True),
    sa.Column('building_level', sa.Integer(), nullable=True),
    sa.Column('building_active', sa.Boolean(), nullable=True),
    sa.Column('building_date_active', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['test_game_buildings.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['test_game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_game_building_progress')
    op.drop_table('test_game_buildings')
    # ### end Alembic commands ###
