"""empty message

Revision ID: c7b9399e3d00
Revises: 1dc48eb0e28d
Create Date: 2024-07-09 23:52:22.665515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7b9399e3d00'
down_revision = '1dc48eb0e28d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_game', schema=None) as batch_op:
        batch_op.drop_column('base_xp_required')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_xp_required', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
