"""empty message

Revision ID: cfb0333442b5
Revises: b1a79ee6255e
Create Date: 2024-07-12 10:11:25.882469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfb0333442b5'
down_revision = 'b1a79ee6255e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_game_cash_log')
    op.drop_table('test_game_xp_log')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_game_xp_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('test_game_id', sa.INTEGER(), nullable=True),
    sa.Column('xp', sa.INTEGER(), nullable=True),
    sa.Column('entry_date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['test_game_id'], ['test_game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_game_cash_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('test_game_id', sa.INTEGER(), nullable=True),
    sa.Column('cash', sa.FLOAT(), nullable=True),
    sa.Column('entry_date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['test_game_id'], ['test_game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
