"""empty message

Revision ID: d236ce32f83c
Revises: 53699ee9f2d0
Create Date: 2024-08-05 10:40:31.544842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd236ce32f83c'
down_revision = '53699ee9f2d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quest_requirements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_level_required', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cash_required', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wood_required', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stone_required', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('metal_required', sa.Integer(), nullable=True))
        batch_op.drop_column('metal')
        batch_op.drop_column('game_level')
        batch_op.drop_column('stone')
        batch_op.drop_column('wood')
        batch_op.drop_column('cash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quest_requirements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cash', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('wood', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('stone', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('game_level', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('metal', sa.INTEGER(), nullable=True))
        batch_op.drop_column('metal_required')
        batch_op.drop_column('stone_required')
        batch_op.drop_column('wood_required')
        batch_op.drop_column('cash_required')
        batch_op.drop_column('game_level_required')

    # ### end Alembic commands ###
