"""empty message

Revision ID: df54d0cc5d66
Revises: 3fc6cd0d160b
Create Date: 2024-07-15 19:53:07.887185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df54d0cc5d66'
down_revision = '3fc6cd0d160b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_game_buildings', schema=None) as batch_op:
        batch_op.alter_column('base_building_cash_required',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_game_buildings', schema=None) as batch_op:
        batch_op.alter_column('base_building_cash_required',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
