"""empty message

Revision ID: e0386229ccea
Revises: 02e07e388520
Create Date: 2024-07-22 21:23:26.554325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0386229ccea'
down_revision = '02e07e388520'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quest_rewards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quest_reward_wood', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('quest_reward_stone', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('quest_reward_metal', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quest_rewards', schema=None) as batch_op:
        batch_op.drop_column('quest_reward_metal')
        batch_op.drop_column('quest_reward_stone')
        batch_op.drop_column('quest_reward_wood')

    # ### end Alembic commands ###
