"""empty message

Revision ID: eebccca79007
Revises: 40ab8cc812e1
Create Date: 2024-07-02 13:59:45.183754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eebccca79007'
down_revision = '40ab8cc812e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_game_inventory_1', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_game_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_test_game_inventory_test_game', 'test_game', ['test_game_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_game_inventory_1', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('test_game_id')

    # ### end Alembic commands ###
