"""empty message

Revision ID: ef580d5fcf6b
Revises: b5e65e5375e1
Create Date: 2024-07-06 10:41:44.381209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef580d5fcf6b'
down_revision = 'b5e65e5375e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_game_quest_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('quest_progress', sa.Integer(), nullable=True),
    sa.Column('quest_active', sa.Boolean(), nullable=True),
    sa.Column('quest_completed', sa.Boolean(), nullable=True),
    sa.Column('quest_completed_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['test_game.id'], ),
    sa.ForeignKeyConstraint(['quest_id'], ['test_game_quests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_game_quest_progress')
    # ### end Alembic commands ###
